In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
print(dataset)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMemb

In [4]:
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [8]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [10]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

Building ANN

In [13]:
ann = tf.keras.models.Sequential()

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation = "relu"))   #addiing input layer and 1st hidden layer, UNITS = neurons

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation = "relu"))    #this is the second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation = "sigmoid"))   #this is the output layer, only one 
#neuron and sigmoid as activation function. If output is non binary, acti. fun is softmax

Training ANN

In [17]:
ann.compile(optimizer = "adam", loss="binary_crossentropy" , metrics= ["accuracy"] )  #catogorical_crossentropy as loss for non binary output (for output more than 2 neurons)

TRAINING ANN ON TRAINING SET

In [18]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 998us/step - loss: 0.5690 - accuracy: 0.7707
Epoch 2/100
250/250 [==============================] - 0s 989us/step - loss: 0.4841 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4556 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 974us/step - loss: 0.4427 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 931us/step - loss: 0.4366 - accuracy: 0.7961
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4332 - accuracy: 0.7958
Epoch 7/100
250/250 [==============================] - 0s 980us/step - loss: 0.4312 - accuracy: 0.7958
Epoch 8/100
250/250 [==============================] - 0s 959us/step - loss: 0.4294 - accuracy: 0.7965
Epoch 9/100
250/250 [==============================] - 0s 931us/step - loss: 0.4266 - accuracy: 0.8010
Epoch 10/100
250/250 [==============================] - 0s 960us/step - loss:

250/250 [==============================] - 1s 2ms/step - loss: 0.3332 - accuracy: 0.8635
Epoch 80/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3333 - accuracy: 0.8636
Epoch 81/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3329 - accuracy: 0.8639
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3331 - accuracy: 0.8630
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3327 - accuracy: 0.8637
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3327 - accuracy: 0.8627
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3329 - accuracy: 0.8641
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3328 - accuracy: 0.8635
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3324 - accuracy: 0.8627
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3330 - accuracy: 

In [19]:
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000,2,1,1,50000]]))>0.5)

[[False]]


thisngs to consider- 1) enter values in [[]], 2) take care of dummy variables, 3) sc.transform to nullify the effect of scaling

In [21]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1512   83]
 [ 190  215]]


0.8635