data preprocessing took


Importing libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

Importing dataset

In [2]:
dataset = pd.read_csv("data.csv")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)
print(dataset)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


Taking care of missing data - if the missing data is 1%, we can ignore them. If missing data is more, we shud take care of it as follows. 

In [3]:
from sklearn.impute import SimpleImputer


SimpleImputer is a class inside sklearn. now i am gonna make an object(which is an instance of class "SimpleImputer" and use it to find missing data)


In [5]:
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean") #imputer is an object, SimpleImputer is a class defined in 
#sklearn package
imputer.fit(x[:, 1:3]) # selecting the columns where i wanna apply this 
x[:, 1:3] = imputer.transform(x[:, 1:3]) #reassigning the values of x to the transformed values
print(x)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [8]:
dataset["Country"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

Encoding catogorical data 

In [10]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import OneHotEncoder 
ct = ColumnTransformer(transformers =[("encoder", OneHotEncoder(),[0])],   remainder="passthrough" )
x = np.array(ct.fit_transform(x)) #the function expects the argument to be np.array
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [12]:
Spliting the data

SyntaxError: invalid syntax (<ipython-input-12-0efc2f38591e>, line 1)

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state = 1)
print(x_train)

[[1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [14]:
print(x_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]]


In [15]:
print(y_train)

[1 0 0 1 1 0 1]


In [16]:
print(y_test)

[0 1 0]


Feature scaling should be applied after the split, as we dont want any interfearance of test data while testing

Feature scaling - some of the models where data is scattered a lot, feature scaling is applied. 
but in some models like multiple linear regressing, there is no need for feature scaling, since the co-efficients associated with big numbers can be controlled.

Feature scaling can be done in 2 ways. 1) Standardisation = (x-mean(x))/SD(x), the range of distribution after this will be between (-l, l) 
2) Normalisation = (x - min(x))/(max(x)-min(x)), range of distribution will be (0,1)
here, standardisation will be used, since its more general.

In [17]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() #no need to apply this technique on dummy values(one hot encoded values). 
x_train[:,3:] = sc.fit_transform(x_train[:,3:])#fit will apply the formula and get mean and SD, but transform will make the changes in x_train
x_test[:,3:] = sc.transform(x_test[:,3:])

In [18]:
print(x_train)

[[1.0 0.0 1.0 -0.6324555320336758 -0.038910211282047996
  -0.22960023388015188]
 [0.0 1.0 0.0 -0.6324555320336758 0.5058327466666259 0.49120534884662787]
 [1.0 0.0 0.0 1.5811388300841895 -0.3112816902563849 -0.4731156334500103]
 [1.0 0.0 0.0 1.5811388300841895 -1.809324824615238 -1.6127677034369463]
 [0.0 1.0 0.0 -0.6324555320336758 1.0505757046152997 1.1048641557626704]
 [1.0 0.0 1.0 -0.6324555320336758 1.3229471835896367 1.455526331143266]
 [0.0 1.0 0.0 -0.6324555320336758 -0.7198389087178904 -0.736112264985457]]


In [19]:
print(x_test)

[[1.0 0.0 1.0 -0.6324555320336758 -1.4007676061537326 -1.0867744403660526]
 [0.0 1.0 0.0 -0.6324555320336758 -0.4474674297435534 0.05287762962088326]
 [1.0 0.0 0.0 1.5811388300841895 -0.20535944843303158 -1.2621055280563505]]
